title: I changed this title
author: CWallis92
email: chriswallis92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm messing around in GitHub and part of that involves getting to grips with GitHub Pages

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima